@startuml diagrama_conceptuala
hide circle
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
skinparam padding 5

entity "Rol" {
  PK id_rol
}

entity "Utilizator" {
  PK id_utilizator
  --
  FK id_rol
}

entity "Categorie" {
  PK id_categorie
}

entity "Curs" {
  PK id_curs
  --
  FK id_instructor
  FK id_categorie
}

entity "Modul" {
  PK id_modul
  --
  FK id_curs
}

entity "Lectie" {
  PK id_lectie
  --
  FK id_modul
}

entity "Inscriere" {
  PK id_inscriere
  --
  FK id_utilizator
  FK id_curs
}

entity "Plata" {
  PK id_plata
  --
  FK id_inscriere
}

entity "Recenzie" {
  PK id_recenzie
  --
  FK id_utilizator
  FK id_curs
}

entity "Test_Evaluare" {
  PK id_test
  --
  FK id_curs
}

entity "Intrebare" {
  PK id_intrebare
  --
  FK id_test
}

entity "Varianta_Raspuns" {
  PK id_varianta
  --
  FK id_intrebare
}

entity "Raspuns_Student" {
  PK id_raspuns
  --
  FK id_utilizator
  FK id_intrebare
  FK id_varianta
}

entity "Certificat" {
  PK id_certificat
  --
  FK id_utilizator
  FK id_curs
}

Utilizator ||--right--o{ Curs
Rol ||--right--o{ Utilizator
Categorie ||--up--o{ Curs

Utilizator ||--down--o{ Inscriere
Curs ||-down-o{ Inscriere
Inscriere ||-down-|| Plata

Utilizator ||--up--o{ Recenzie
Recenzie }o--right--|| Curs

Utilizator ||--up--o{ Certificat
Certificat }o--right--|| Curs

Curs ||--right--o{ Modul
Modul ||--right--o{ Lectie

Curs ||--up--|| Test_Evaluare
Test_Evaluare ||--down--o{ Intrebare
Intrebare ||--down--o{ Varianta_Raspuns

Utilizator ||-down-o{ Raspuns_Student
Intrebare ||--right--o{ Raspuns_Student
Varianta_Raspuns ||--up--o{ Raspuns_Student

@enduml